#!/usr/bin/env python
import dropbox
import sys

# Initialize Dropbox client with an access token
dbx = dropbox.Dropbox('')

# Function to list all files URLs in a folder
def list_files_urls(folder_path):
    files = dbx.files_list_folder(folder_path).entries
    for file in files:
        if isinstance(file, dropbox.files.FileMetadata):
            file_url = dbx.files_get_temporary_link(file.path_lower).link
            print(file_url)

# Call the function with the specified folder path
list_files_urls(sys.argv[1])

